# Generated by Django 4.2.1 on 2023-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('ygn', 'Yangon'), ('mdy', 'Mandalay'), ('pol', 'MayMyo'), ('bgo', 'Bago')], default=2, max_length=20, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=12, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'owner'), (2, 'agency'), (3, 'client'), (4, 'renter'), (5, 'advertiser')]),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
