# Generated by Django 4.2.1 on 2023-09-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('google_map', models.URLField(max_length=400)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_supply', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('play_ground', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp/property')),
                ('caption', models.CharField(max_length=40)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
