# Generated by Django 4.2.1 on 2023-09-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='owner')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Apartment'), (1, 'Condo'), (2, 'Home'), (3, 'Land'), (4, 'For Industrial'), (5, 'Farm Field')], default=2, verbose_name='property type')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Listing'), (1, 'Sold'), (2, 'Rendering')], default=0, verbose_name='status')),
                ('city', models.CharField(choices=[('ygn', 'Yangon'), ('mdy', 'Mandalay'), ('pol', 'MayMyo'), ('bgo', 'Bago')], max_length=8, null=True, verbose_name='city')),
                ('google_map', models.URLField(max_length=400, verbose_name='google_map')),
                ('square_feet', models.CharField(max_length=10, verbose_name='square feet')),
                ('price', models.IntegerField()),
                ('bedroom', models.PositiveSmallIntegerField(default=0, verbose_name='How many do bedroom have?')),
                ('bathroom', models.PositiveSmallIntegerField(default=0, verbose_name='How many do bathroom have?')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift', models.BooleanField(default=False, verbose_name='lift')),
                ('security_guard', models.BooleanField(default=False, verbose_name='security_guard')),
                ('water_supply', models.BooleanField(default=False, verbose_name='water supply')),
                ('power_backup', models.BooleanField(default=False, verbose_name='power backup')),
                ('garden', models.BooleanField(default=False, verbose_name='garden')),
                ('play_ground', models.BooleanField(default=False, verbose_name='play ground')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.BooleanField(default=False, verbose_name='gym')),
                ('school', models.BooleanField(default=False, verbose_name='school')),
                ('market', models.BooleanField(default=False, verbose_name='Market Place')),
                ('mall', models.BooleanField(default=False, verbose_name='Shopping Mall')),
                ('hospital', models.BooleanField(default=False, verbose_name='hospital')),
                ('parking', models.BooleanField(default=False, verbose_name='parking')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp/property')),
                ('caption', models.CharField(max_length=40)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
