# Generated by Django 4.2.1 on 2023-09-13 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(0, 'for sale'), (1, 'for rent'), (2, 'for buy')], default=0, verbose_name='for what?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_properties', related_query_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_map',
            field=models.URLField(max_length=400, verbose_name='google map'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Listing'), (1, 'Sold'), (2, 'Rendering')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Apartment'), (1, 'Condo'), (2, 'Home'), (3, 'Land'), (4, 'For Industrial'), (5, 'Farm Field')], verbose_name='property type'),
        ),
    ]
