# Generated by Django 4.2.1 on 2023-09-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_image_property_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearby',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='gym'),
        ),
        migrations.AlterField(
            model_name='nearby',
            name='school',
            field=models.BooleanField(default=False, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='service',
            name='garden',
            field=models.BooleanField(default=False, verbose_name='garden'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='play_ground',
            field=models.BooleanField(default=False, verbose_name='play ground'),
        ),
        migrations.AlterField(
            model_name='service',
            name='power_backup',
            field=models.BooleanField(default=False, verbose_name='power supply'),
        ),
        migrations.AlterField(
            model_name='service',
            name='water_supply',
            field=models.BooleanField(default=False, verbose_name='water supply'),
        ),
    ]
