# Generated by Django 4.2.1 on 2023-09-07 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_nearby_gym_alter_nearby_school_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='parking',
        ),
        migrations.AddField(
            model_name='nearby',
            name='hospital',
            field=models.BooleanField(default=False, verbose_name='hospital'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='How many do bathroom have?'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='How many do bedroom have?'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('ygn', 'Yangon'), ('mdy', 'Mandalay'), ('pol', 'MayMyo'), ('bgo', 'Bago')], max_length=8, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, max_length=50, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.CharField(default=0, max_length=10, verbose_name='square feet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Listing'), (1, 'Sold'), (2, 'Rendering')], default=0, verbose_name='property type'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Apartment'), (1, 'Condo'), (2, 'Home'), (3, 'Land'), (4, 'For Industrial'), (5, 'Farm Field')], default=2, verbose_name='property type'),
        ),
        migrations.AddField(
            model_name='service',
            name='lift',
            field=models.BooleanField(default=False, verbose_name='lift'),
        ),
        migrations.AddField(
            model_name='service',
            name='security_guard',
            field=models.BooleanField(default=False, verbose_name='security_guard'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=300, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_map',
            field=models.URLField(max_length=400, verbose_name='google_map'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='power_backup',
            field=models.BooleanField(default=False, verbose_name='power backup'),
        ),
    ]
